### ISSUE TITLE
/path/to/project1/.rancher-shell.yml ?

### ISSUE THREAD

**Issue by PhanQ** [marcqualie/rancher-shell#1]
Hello, could you help explain exactly /path/to/project1 means?
/path/to/project1/.rancher-shell.yml

**Comment by marcqualie** [comment]
That is the root of your project if you want project specific configurations. May be easier to think of it as folder specific, I.e. If a folder contains .rancher-shell.yml file it will combine and override the one in your user directory. I use this so if I am in the folder for a specific project I can just run "rancher-shell" without any options to auto connect to that project's environment.

**Comment by PhanQ** [comment]
Got it! Now I get error SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError), although it seems you already changed verify mode to NONE in code ctx.verify_mode = options[:verify_mode] || OpenSSL::SSL::VERIFY_NONE

**Comment by marcqualie** [comment]
Does your server have SSL? Verify none will only allow self signed certificates, it will still fail for standard http connections. I am currently using this on both valid and self signed servers for different projects. It may also be worth checking if you are behind a proxy or firewall that prevents SSLv3 connections as that is the error that is thrown by the looks of it

**Comment by PhanQ** [comment]
I can bypass SSL error by setting "use_ssl: false" in api.rb. One thing in this file is that I have to hardcode project value, don't know how to get it config file, #{@options[:project]} doesn't work.
Now I can get running container list by calling: rancher-shell list-containers
But when I call rancher-shell exec, I get the error:
INFO -- : container = 1i3177
DEBUG -- : running command: bundle exec rails console
INFO -- : connecting to ws://[rancher_server]/v1/exec/ ...
INFO -- : listening
INFO -- :   connected!
                                             /bin/sh: bundle: command not found 
I tried to export ENV PATH /usr/local/rvm/gems/ruby-2.2.1/bin:$PATH in bashrc but it doesn't work.
Please help! Thank you.

**Comment by marcqualie** [comment]
Could you please verify what you mean by not being able to get the project value?

**Comment by PhanQ** [comment]
@marcqualie Have you ever tried to bring rancher-shell to a web UI?

**Comment by marcqualie** [comment]
I do have more plans for this when I get the time. I currently have it also working as a chrome extension so I can quickly jump into shells from the browser to do quick one liners.

A web UI would take more work such as authentication/accounts etc so I've not done any work on that yet.
